main: Socio.o main.o Mascota.o Consulta.o
	g++ Socio.o main.o Mascota.o Consulta.o

Socio.o: Socio.cpp

main.o: main.cpp

Mascota.o: Mascota.cpp

Consulta.o: Consulta.cpp

clean-w:
	del /Q *.o 
	del /Q main.exe

clean:
	rm -rf *.o grin
	clear

