main: DtFecha.o DtMascota.o Gato.o Perro.o Socio.o Mascota.o Consulta.o main.o 
	g++ DtFecha.o DtMascota.o Gato.o Perro.o Socio.o Mascota.o Consulta.o main.o

DtFecha: DtFecha.cpp

DtMascota: DtMascota.cpp

Gato.o: Gato.cpp

Perro.o: Perro.cpp

Mascota.o: Mascota.cpp

Consulta.o: Consulta.cpp

Socio.o: Socio.cpp

main.o: main.cpp

clean-w:
	del /Q *.o 
	del /Q main.exe

clean:
	rm -rf *.o grin
	clear

